# Site
name: "A Wondering Wanderer"
description: "Breaking stereotypes, constantly seeking wisdom, new experiences and growth"
meta_description: ""
logo_header: 'assets/images/logo_header.png'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'



# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
category_archive:
  type: liquid
<<<<<<< HEAD
  path: /_site/category/
=======
  path: /category/
>>>>>>> 68b76c9c3692ff6ad144d7222e9a4ac94de08f52
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
