# Site
name: "A Wondering Wanderer"
description: "Breaking stereotypes, constantly seeking wisdom, new experiences and growth"
meta_description: ""
logo_header: 'assets/images/logo_header.png'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-133578297-1'
disqus: 'aishwaryapanchal'
mailchimp-list: ''



# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
category_archive:
  type: liquid
  path: /category/
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
